import {
  fluentButton,
  fluentCard,
  fluentCheckbox,
  fluentCombobox,
  fluentDialog,
  fluentNumberField,
  fluentOption,
  fluentProgressRing,
  fluentRadio,
  fluentRadioGroup,
  fluentSelect,
  fluentTab,
  fluentTabPanel,
  fluentTabs,
  fluentTextField,
  provideFluentDesignSystem,
} from "@fluentui/web-components";

provideFluentDesignSystem().register(
  fluentButton(),
  fluentCard(),
  fluentCheckbox(),
  fluentCombobox(),
  fluentDialog(),
  fluentNumberField(),
  fluentOption(),
  fluentProgressRing(),
  fluentRadio(),
  fluentRadioGroup(),
  fluentSelect(),
  fluentTab(),
  fluentTabPanel(),
  fluentTabs(),
  fluentTextField(),
);
